In [1]:
from ngsolve import *
from ngsolve.webgui import Draw
from netgen.occ import *
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp
from netgen.csg import Pnt


In [2]:
#help(unit_square)
netgen_mesh = unit_square.GenerateMesh(maxh=0.25)
#print(netgen_mesh.MacroElementNr(...))

mesh = Mesh(netgen_mesh)
#help(mesh)
#issues with this-> maskes certain spaces not work
# mesh.Refine()
# mesh.Refine()
# mesh.Refine()
#other spaces dont work

#might need to be number of faces (in unrefined mesh) because elements are have 1 face
unref_dofnr = mesh.ne #mesh.ne
print(unref_dofnr)
Draw(mesh)

34


WebGuiWidget(layout=Layout(height='500px', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.2…

BaseWebGuiScene

In [3]:


mesh.ngmesh.SplitPowellSabin()
mesh.ngmesh.Update()

#mesh._updateBuffers()


H_h = Compress(L2(mesh,order=0))
 



#might need to be number of faces in barycentrically refined mesh
bary_dofnr = H_h.ndof #mesh.ne
print(bary_dofnr)

#mesh._updateBuffers()


Draw(mesh)

204


WebGuiWidget(layout=Layout(height='500px', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.2…

BaseWebGuiScene

In [4]:
#H_h = H1(mesh,order=1)
#help(H_h.Prolongation())

In [5]:
# for el in mesh.Elements():
#     print(el.nr)
    #print(len(H_h.GetDofNrs(el)))
    #print(mesh.GetParentElement(el))
    # for v in el.vertices:
    #     print(v.nr)
    # print(el.edges)
    # print(el.faces)

for f in mesh.faces:
    print(f,f.vertices)

F0 (V0, V4, V15)
F1 (V1, V6, V18)
F2 (V1, V7, V18)
F3 (V2, V9, V10)
F4 (V3, V12, V13)
F5 (V4, V5, V16)
F6 (V4, V15, V16)
F7 (V5, V6, V17)
F8 (V5, V16, V17)
F9 (V6, V17, V18)
F10 (V7, V8, V19)
F11 (V7, V18, V19)
F12 (V8, V9, V20)
F13 (V8, V19, V20)
F14 (V9, V10, V20)
F15 (V10, V11, V21)
F16 (V10, V20, V21)
F17 (V11, V12, V22)
F18 (V11, V21, V22)
F19 (V12, V13, V22)
F20 (V13, V14, V22)
F21 (V14, V15, V23)
F22 (V14, V22, V23)
F23 (V15, V16, V23)
F24 (V16, V17, V24)
F25 (V16, V23, V24)
F26 (V17, V18, V24)
F27 (V18, V19, V24)
F28 (V19, V20, V25)
F29 (V19, V24, V25)
F30 (V20, V21, V25)
F31 (V21, V22, V25)
F32 (V22, V23, V25)
F33 (V23, V24, V25)
F34 (V0, V26, V29)
F35 (V0, V28, V29)
F36 (V1, V40, V43)
F37 (V1, V40, V48)
F38 (V1, V42, V43)
F39 (V1, V46, V48)
F40 (V2, V61, V64)
F41 (V2, V63, V64)
F42 (V3, V75, V78)
F43 (V3, V77, V78)
F44 (V4, V26, V29)
F45 (V4, V27, V29)
F46 (V4, V27, V95)
F47 (V4, V30, V33)
F48 (V4, V32, V33)
F49 (V4, V32, V95)
F50 (V5, V30, V33)
F51 (V5, V31, V33)
F52 (V5, V3

In [6]:
 #H_h.ndof//mesh.ne
# print(netgen_mesh.dim)
#bary_dofnr//unref_dofnr == 6 (for L2)
children = np.empty((unref_dofnr,6),dtype=np.int64)

indices = np.zeros(unref_dofnr, dtype=np.int64)

for el in mesh.Elements():
    #print(el.nr)
    parent = netgen_mesh.MacroElementNr(el.nr)
    for dofnr in H_h.GetDofNrs(el):
        children[parent,indices[parent]] = dofnr
        indices[parent] += 1
    #help(el)
    #break

print(children)


[[  0  34  35  36  37  38]
 [  1  39  40  41  42  43]
 [  2  44  45  46  47  48]
 [  3  49  50  51  52  53]
 [  4  54  55  56  57  58]
 [  5  59  60  61  62  63]
 [  6  64  65  66  67  68]
 [  7  69  70  71  72  73]
 [  8  74  75  76  77  78]
 [  9  79  80  81  82  83]
 [ 10  84  85  86  87  88]
 [ 11  89  90  91  92  93]
 [ 12  94  95  96  97  98]
 [ 13  99 100 101 102 103]
 [ 14 104 105 106 107 108]
 [ 15 109 110 111 112 113]
 [ 16 114 115 116 117 118]
 [ 17 119 120 121 122 123]
 [ 18 124 125 126 127 128]
 [ 19 129 130 131 132 133]
 [ 20 134 135 136 137 138]
 [ 21 139 140 141 142 143]
 [ 22 144 145 146 147 148]
 [ 23 149 150 151 152 153]
 [ 24 154 155 156 157 158]
 [ 25 159 160 161 162 163]
 [ 26 164 165 166 167 168]
 [ 27 169 170 171 172 173]
 [ 28 174 175 176 177 178]
 [ 29 179 180 181 182 183]
 [ 30 184 185 186 187 188]
 [ 31 189 190 191 192 193]
 [ 32 194 195 196 197 198]
 [ 33 199 200 201 202 203]]


In [7]:
#L2 fine to coarse mapping

data_length = mesh.ne
data = np.zeros(data_length)
row_ind = np.zeros(data_length, dtype=int)
col_ind = np.zeros(data_length, dtype=int)

j = 0

for el in mesh.Elements():
    #print(el.nr)
    parent = netgen_mesh.MacroElementNr(el.nr)
    for dofnr in H_h.GetDofNrs(el):
        row_ind[j] = parent
        col_ind[j] = dofnr
        data[j] = 1
        j += 1
    #help(el)
    #break

ng_mat = la.SparseMatrixdouble.CreateFromCOO(row_ind,col_ind,data, mesh.ne//6,mesh.ne)
print(ng_mat.ToDense())

       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       1       1       1       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0

In [8]:
dfu = GridFunction(H_h,multidim = unref_dofnr)
#help(ng_mat)



dfu.Set(0)
for i in range(unref_dofnr):
    #print(ng_mat.ToDense().NumPy()[:,i])
    dfu.vecs[:][i] = ng_mat.ToDense().NumPy()[i,:]


# for i in range(4):
    #print(dfu.vecs[i][:].FV().NumPy())

Draw(dfu, animate = True, min = 0, max = 0.5, deformation = False)

WebGuiWidget(layout=Layout(height='500px', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.2…

BaseWebGuiScene

In [9]:
#H_h = L2(mesh,order=0) 
 


gfu = GridFunction(H_h,multidim = unref_dofnr)



In [10]:
#help(mesh)

# for el in mesh.Elements():    
#     dofnr = H_h.GetDofNrs(el)
#     #print(H_h.GetDofNrs(el.faces[0])) #same result as above as each element only contains 1 face
#     print(dofnr)

In [11]:
# print(H_h.ndof)

# for i in range(unref_dofnr):
#     for j in children[i,:]:
#         #print(j)
#         gfu.vecs[i][j] = 2.0


# Draw(gfu, animate = True, min = 0, max = 2.0, deformation = False)

Dual

In [12]:
H_h = H1(mesh, order=1)

In [13]:
data_length = mesh.ne * 7
data = np.zeros(data_length)
row_ind = np.zeros(data_length, dtype=int)
col_ind = np.zeros(data_length, dtype=int)
shape = (mesh.ne/6,mesh.nv)

j = 0

for el in mesh.Elements():
    #print(el.nr)
    parent = netgen_mesh.MacroElementNr(el.nr)
    for v in el.vertices:
        ver = mesh.__getitem__(v)
        dofnr = H_h.GetDofNrs(ver)
        row_ind[j] = parent
        col_ind[j] = dofnr[0]
        data[j] = 1/len(ver.elements)
        j += 1
    #help(el)
    #break



ng_mat = la.SparseMatrixdouble.CreateFromCOO(row_ind,col_ind,data, mesh.ne//6,mesh.nv)
print(ng_mat.ToDense())

       1       0       0       0 0.333333       0       0       0       0       0       0       0       0       0       0    0.25       0       0       0       0       0       0       0       0       0       0       1     0.5       1       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0
       0       0       0       0 0.333333 0.33

In [14]:
dfu = GridFunction(H_h,multidim = unref_dofnr)
#help(ng_mat)



dfu.Set(0)
for i in range(unref_dofnr):
    #print(ng_mat.ToDense().NumPy()[:,i])
    dfu.vecs[:][i] = ng_mat.ToDense().NumPy()[i,:]


# for i in range(4):
    #print(dfu.vecs[i][:].FV().NumPy())

Draw(dfu, animate = True, min = 0, max = 1, deformation = False)

WebGuiWidget(layout=Layout(height='500px', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.2…

BaseWebGuiScene